"""add cooldown record

迁移 ID: 4d3ca10a3be8
父迁移: dc8d05807856
创建时间: 2025-10-23 22:14:01.393201

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "4d3ca10a3be8"
down_revision: str | Sequence[str] | None = "dc8d05807856"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_setu_now_cooldownrecord",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("last_use_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint(
            "user_id", name=op.f("pk_nonebot_plugin_setu_now_cooldownrecord")
        ),
        info={"bind_key": "nonebot_plugin_setu_now"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_setu_now_cooldownrecord")
    # ### end Alembic commands ###
