"""change GroupWhiteListRecord

迁移 ID: 4f9463d0ecb0
父迁移: 4d3ca10a3be8
创建时间: 2025-10-23 23:09:35.517294

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "4f9463d0ecb0"
down_revision: str | Sequence[str] | None = "4d3ca10a3be8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_setu_now_groupwhitelistrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "group_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "operator_user_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_setu_now_groupwhitelistrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "operator_user_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "group_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
