"""first revision

迁移 ID: dc8d05807856
父迁移:
创建时间: 2025-10-23 19:04:52.135908

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "dc8d05807856"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_setu_now_groupwhitelistrecord",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("operator_user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "group_id", name=op.f("pk_nonebot_plugin_setu_now_groupwhitelistrecord")
        ),
        info={"bind_key": "nonebot_plugin_setu_now"},
    )
    op.create_table(
        "nonebot_plugin_setu_now_messageinfo",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "message_id", name=op.f("pk_nonebot_plugin_setu_now_messageinfo")
        ),
        info={"bind_key": "nonebot_plugin_setu_now"},
    )
    op.create_table(
        "nonebot_plugin_setu_now_setuinfo",
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint(
            "pid", name=op.f("pk_nonebot_plugin_setu_now_setuinfo")
        ),
        info={"bind_key": "nonebot_plugin_setu_now"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_setu_now_setuinfo")
    op.drop_table("nonebot_plugin_setu_now_messageinfo")
    op.drop_table("nonebot_plugin_setu_now_groupwhitelistrecord")
    # ### end Alembic commands ###
